const phases=["DRAW PHASE","STANDBY PHASE","MAIN PHASE 1","BATTLE PHASE","MAIN PHASE 2","END PHASE"];
const CARD_BACK="assets/cards/card-back.jpg";
let cards=[]; let state=null; let selectedDiff="easy";

function escapeHTML(text){return String(text??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;}
function cardVisual(card,extra=""){if(!card)return "";const monster=(card.type||"monster")==="monster";const level=Math.max(0,Number(card.level||0));const stars=monster&&level?"★".repeat(Math.min(level,12)):"";const type=card.type==="spell"?"MAGIC CARD":card.type==="trap"?"TRAP CARD":"MONSTER CARD";return `<div class="duel-card ${extra} ${monster?"monster-card":"effect-card"}"><div class="duel-card-name">${escapeHTML(card.name||"CARTA")}</div>${monster&&card.attribute?`<div class="duel-card-attribute">${escapeHTML(card.attribute)}</div>`:""}${monster?`<div class="duel-card-level">${stars}</div>`:""}<div class="duel-card-art">${card.image?`<img src="${card.image}" alt="${escapeHTML(card.name||"Carta")}">`:`<div class="card-art-missing">SEM IMAGEM</div>`}</div><div class="duel-card-info"><div class="duel-card-type">[${escapeHTML(card.race||type)}]</div><div class="duel-card-effect">${escapeHTML(card.description||"Sem efeito cadastrado.")}</div>${monster?`<div class="duel-card-stats"><span>ATK ${card.atk??"—"}</span><span>DEF ${card.def??"—"}</span></div>`:""}</div></div>`;}
function backVisual(extra=""){return `<div class="card-back ${extra}" style="background-image:url('${CARD_BACK}')"></div>`;}
function screen(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));document.getElementById(id)?.classList.add("active");}
function log(m){const e=document.getElementById("log");if(e)e.innerHTML=`<div>${escapeHTML(m)}</div>`+e.innerHTML;}
function playerName(p){return state?.twoPlayers?(p===0?"JOGADOR 1":"JOGADOR 2"):(p===0?"VOCÊ":"BOT");}
function makeDeck(){if(!cards.length){alert("As cartas ainda estão carregando.");return [];}return shuffle(shuffle(cards).slice(0,30));}

document.addEventListener("DOMContentLoaded",()=>{
 document.querySelectorAll(".difficulty button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".difficulty button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selectedDiff=b.dataset.diff||"easy";}));
 fetch("data/cards.json").then(r=>{if(!r.ok)throw Error("cards.json");return r.json();}).then(d=>{cards=d;const c=document.getElementById("cardCount");if(c)c.textContent=`${cards.length} CARTAS`;}).catch(e=>{console.error(e);alert("Erro ao carregar cartas. Execute com server.js ou npx serve .");});
});
function showDeck(){screen("deckScreen");renderDeck();}
function backMenu(){if(state&&!confirm("Voltar ao menu?"))return;state=null;screen("menu");}
function renderDeck(){const g=document.getElementById("deckGrid");if(!g)return;const q=(document.getElementById("search")?.value||"").toLowerCase().trim();g.innerHTML=cards.filter(c=>(c.name||"").toLowerCase().includes(q)).map(c=>`<div class="card-preview full-card-preview">${cardVisual(c)}</div>`).join("");}

function startBot(){startGame(false);} function startTwoPlayers(){startGame(true);}
function startGame(twoPlayers){const d1=makeDeck(),d2=makeDeck();if(!d1.length||!d2.length)return;state={twoPlayers,turn:1,activePlayer:0,phase:0,lp:[4000,4000],decks:[d1,d2],hands:[[],[]],fields:[Array(6).fill(null),Array(6).fill(null)],graveyards:[[],[]],selectedHand:null,selectedAttacker:null,animatingBattle:false,gameOver:false,attacked:[new Set(),new Set()]};state.hands[0]=state.decks[0].splice(0,5);state.hands[1]=state.decks[1].splice(0,5);document.getElementById("oppName").textContent=twoPlayers?"JOGADOR 2":"BOT • "+selectedDiff.toUpperCase();document.getElementById("myName").textContent="JOGADOR 1";screen("duel");log(twoPlayers?"Duelo para 2 jogadores iniciado.":"Duelo contra BOT iniciado.");render();beginTurn(0);}
function beginTurn(p){if(!state||state.gameOver)return;state.activePlayer=p;state.phase=0;state.selectedHand=null;state.selectedAttacker=null;state.attacked[p]=new Set();closeActions();if(state.decks[p].length){const c=state.decks[p].shift();state.hands[p].push(c);log(`${playerName(p)} comprou uma carta.`);}else log(`${playerName(p)} está sem cartas no monte.`);render();if(state.twoPlayers)showWaitScreen(p);else if(p===1)setTimeout(botTurn,700);else log("MAIN PHASE: selecione uma carta da mão.");}
function showWaitScreen(p){const m=document.getElementById("waitModal");if(!m)return;m.querySelector("h2").textContent=`VEZ DO ${playerName(p)}`;m.querySelector("p").textContent="Passe o aparelho para o jogador e comece o turno.";const b=m.querySelector("button");b.textContent="COMEÇAR TURNO";b.onclick=()=>{m.classList.add("hidden");render();};m.classList.remove("hidden");}
function closeWait(){document.getElementById("waitModal")?.classList.add("hidden");}
function render(){if(!state)return;document.getElementById("turnLabel").textContent=`TURNO ${state.turn}`;document.getElementById("phaseLabel").textContent=phases[state.phase];document.getElementById("oppLP").textContent=state.lp[1];document.getElementById("myLP").textContent=state.lp[0];document.getElementById("oppBar").style.width=`${Math.max(0,state.lp[1]/40)}%`;document.getElementById("myBar").style.width=`${Math.max(0,state.lp[0]/40)}%`;document.getElementById("oppDeckCount").textContent=state.decks[1].length;document.getElementById("myDeckCount").textContent=state.decks[0].length;document.getElementById("oppGraveCount").textContent=state.graveyards[1].length;document.getElementById("myGraveCount").textContent=state.graveyards[0].length;drawZones(0,"myZones");drawZones(1,"oppZones");drawHand(0,"myHand");drawHand(1,"oppHand");updateInspector();}
function drawZones(p,id){const e=document.getElementById(id);if(!e)return;e.innerHTML=state.fields[p].map((entry,i)=>{if(!entry)return `<div class="zone empty-zone"><span>${i+1}</span></div>`;return `<div class="zone occupied"><button class="field-card ${entry.faceUp?"face-up":"face-down"}" onclick="selectFieldCard(${p},${i})" title="${escapeHTML(entry.card.name)}">${entry.faceUp?cardVisual(entry.card):backVisual()}</button><small>${entry.faceUp?(entry.position||"ATK"):"FACE BAIXO"}</small></div>`;}).join("");}
function drawHand(p,id){const e=document.getElementById(id);if(!e)return;if(p===1){e.innerHTML=state.hands[1].map(()=>`<div class="hand-card-back-img">${backVisual()}</div>`).join("");return;}e.innerHTML=state.hands[0].map((c,i)=>`<button class="hand-card full-hand-card ${state.selectedHand===i?"hand-selected":""}" onclick="selectHand(${i})" title="${escapeHTML(c.name)}">${cardVisual(c)}</button>`).join("");}
function selectHand(i){if(!state||state.activePlayer!==0||state.phase<2||state.phase>4)return;state.selectedHand=i;const c=state.hands[0][i];state.inspectedCard=c;document.getElementById("selectedCardName").textContent=c.name;document.getElementById("cardActions").classList.remove("hidden");updateInspector();render();}
function cancelSelection(){state.selectedHand=null;closeActions();render();} function closeActions(){document.getElementById("cardActions")?.classList.add("hidden");}
function updateInspector(){const b=document.getElementById("cardInspector");if(!b)return;const c=state?.inspectedCard;b.innerHTML=c?cardVisual(c):`<div class="inspector-empty">Selecione uma carta</div>`;}
function placeSelected(faceUp){if(!state||state.activePlayer!==0||state.selectedHand===null)return;const c=state.hands[0][state.selectedHand];if(!c)return;const slot=state.fields[0].findIndex(x=>!x);if(slot<0){log("As 6 zonas estão ocupadas.");return;}if(c.type!=="monster"&&!faceUp){state.fields[0][slot]={card:c,faceUp:false,position:"SET"};state.hands[0].splice(state.selectedHand,1);state.graveyards[0]=state.graveyards[0];log(`Você colocou ${c.name} virada para baixo.`);}else if(c.type==="monster"){state.fields[0][slot]={card:c,faceUp,position:faceUp?"ATK":"DEF"};state.hands[0].splice(state.selectedHand,1);log(`Você colocou ${c.name} ${faceUp?"face para cima":"face para baixo"}.`);}else{state.hands[0].splice(state.selectedHand,1);const damage=150+Math.floor(Math.random()*351);state.lp[1]=Math.max(0,state.lp[1]-damage);state.graveyards[0].push(c);log(`Você ativou ${c.name}: -${damage} LP.`);checkWin();}state.selectedHand=null;closeActions();render();}
function nextPhase(){if(!state||state.gameOver||state.activePlayer!==0)return;if(state.phase<5){state.phase++;render();log(`${playerName(0)} entrou em ${phases[state.phase]}.`);}}
function endTurn(){if(!state||state.gameOver||state.activePlayer!==0)return;closeActions();state.selectedHand=null;if(state.twoPlayers){state.turn++;beginTurn(1);}else{state.activePlayer=1;state.phase=0;render();setTimeout(botTurn,500);}}
function selectFieldCard(p,i){if(!state||state.gameOver||state.animatingBattle)return;const e=state.fields[p][i];if(!e)return;if(p===0&&state.activePlayer===0){if(!e.faceUp||e.card.type!=="monster"){log("Essa carta não pode atacar enquanto estiver virada para baixo.");return;}if(state.phase<3){log("Entre na BATTLE PHASE para atacar.");return;}if(state.attacked[0].has(i)){log("Esse monstro já atacou neste turno.");return;}state.selectedAttacker=i;log(`${e.card.name} selecionado. Toque em um monstro inimigo ou use ataque direto.`);render();return;}if(p===1&&state.activePlayer===0&&state.selectedAttacker!==null){if(!e.faceUp){log("O alvo está virado para baixo.");return;}resolveBattle(0,state.selectedAttacker,1,i);}}
function directAttack(){if(!state||state.gameOver||state.activePlayer!==0||state.phase<3)return;const i=state.selectedAttacker??state.fields[0].findIndex(e=>e?.faceUp&&e.card.type==="monster");const a=state.fields[0][i];if(!a)return;if(state.fields[1].some(Boolean)){log("Ainda existem cartas no campo inimigo.");return;}if(state.attacked[0].has(i))return;state.attacked[0].add(i);state.selectedAttacker=null;const dmg=Math.max(100,Number(a.card.atk||0));state.lp[1]=Math.max(0,state.lp[1]-dmg);animateBattle(a.card,null,dmg,true,()=>{log(`${a.card.name} atacou diretamente: -${dmg} LP.`);render();checkWin();});}
function resolveBattle(ap,ai,tp,ti,done){if(!state||state.animatingBattle)return;const a=state.fields[ap][ai],t=state.fields[tp][ti];if(!a||!t||!a.faceUp||!t.faceUp)return;state.selectedAttacker=null;state.attacked[ap].add(ai);const aa=Number(a.card.atk||0),tt=Number(t.card.atk||0);let dmg=0,msg="";if(aa>tt){dmg=aa-tt;state.lp[tp]=Math.max(0,state.lp[tp]-dmg);state.graveyards[tp].push(t.card);state.fields[tp][ti]=null;msg=`${a.card.name} destruiu ${t.card.name}: -${dmg} LP.`;}else if(aa<tt){dmg=tt-aa;state.lp[ap]=Math.max(0,state.lp[ap]-dmg);state.graveyards[ap].push(a.card);state.fields[ap][ai]=null;msg=`${t.card.name} destruiu ${a.card.name}: -${dmg} LP.`;}else{state.graveyards[ap].push(a.card);state.graveyards[tp].push(t.card);state.fields[ap][ai]=null;state.fields[tp][ti]=null;msg=`Empate: ${a.card.name} e ${t.card.name} foram para o cemitério.`;}animateBattle(a.card,t.card,dmg,false,()=>{log(msg);render();if(!checkWin()&&done)done();});}
function animateBattle(attacker,target,damage,isDirect,cb){const b=document.getElementById("virtualBattle"),ab=document.getElementById("battleAttacker"),tb=document.getElementById("battleTarget"),im=document.getElementById("battleImpact"),cap=document.getElementById("battleCaption"),dg=document.getElementById("battleDamage");if(!b||!ab||!tb){cb?.();return;}state.animatingBattle=true;b.classList.remove("hidden","battle-run");ab.innerHTML=cardVisual(attacker,"battle-card");tb.innerHTML=target?cardVisual(target,"battle-card"):"";tb.style.display=target?"block":"none";cap.textContent=isDirect?"ATAQUE DIRETO!":"ATAQUE!";im.textContent=damage?"⚡":"💥";dg.textContent=damage?`-${damage} LP`:"DESTRUIÇÃO";im.classList.remove("show-impact");dg.classList.remove("show-damage");void b.offsetWidth;b.classList.add("battle-run");im.classList.add("show-impact");dg.classList.add("show-damage");setTimeout(()=>{b.classList.add("hidden");b.classList.remove("battle-run");im.classList.remove("show-impact");dg.classList.remove("show-damage");ab.innerHTML="";tb.innerHTML="";tb.style.display="block";state.animatingBattle=false;cb?.();},1550);}
function botTurn(){if(!state||state.gameOver||state.animatingBattle)return;state.activePlayer=1;state.phase=2;state.selectedAttacker=null;if(state.decks[1].length){state.hands[1].push(state.decks[1].shift());log("BOT comprou uma carta.");}const mi=state.hands[1].findIndex(c=>c.type==="monster");const slot=state.fields[1].findIndex(x=>!x);if(mi>=0&&slot>=0){const c=state.hands[1].splice(mi,1)[0];state.fields[1][slot]={card:c,faceUp:true,position:"ATK"};log(`BOT invocou ${c.name}.`);}render();setTimeout(()=>{if(!state||state.gameOver)return;const ai=state.fields[1].findIndex(e=>e?.faceUp&&e.card.type==="monster");if(ai<0){finishBotTurn();return;}const ti=state.fields[0].findIndex(Boolean);if(ti>=0&&state.fields[0][ti].faceUp){resolveBattle(1,ai,0,ti,finishBotTurn);return;}if(ti<0){const a=state.fields[1][ai];const dmg=Math.max(100,Number(a.card.atk||0));state.lp[0]=Math.max(0,state.lp[0]-dmg);animateBattle(a.card,null,dmg,true,()=>{log(`BOT atacou diretamente: -${dmg} LP.`);render();if(!checkWin())finishBotTurn();});return;}finishBotTurn();},600);}
function finishBotTurn(){if(!state||state.gameOver)return;state.turn++;beginTurn(0);}
function checkWin(){if(!state)return false;let w=null;if(state.lp[0]<=0)w=state.twoPlayers?"JOGADOR 2":"BOT";if(state.lp[1]<=0)w="JOGADOR 1";if(!w)return false;state.gameOver=true;const m=document.getElementById("waitModal");m.querySelector("h2").textContent=`${w} VENCEU!`;m.querySelector("p").textContent="O duelo terminou.";const b=m.querySelector("button");b.textContent="VOLTAR AO MENU";b.onclick=()=>{m.classList.add("hidden");state=null;screen("menu");};m.classList.remove("hidden");return true;}
function confirmExit(){if(confirm("Sair do duelo?")){state=null;screen("menu");}}
